src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $Id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Serie = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTime $Date_Mise_En_Marche = null;

    #[ORM\Column]
    private ?float $Prix_jour = null;

    /**
     * @var Collection<int, Location>
     */
    #[ORM\OneToMany(targetEntity: Location::class, mappedBy: 'voiture')]
    private Collection $locations;

    #[ORM\ManyToOne(inversedBy: 'Voitures')]
    private ?Modele $modele = null;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->Id;
    }

    public function setId(int $Id): static
    {
        $this->Id = $Id;

        return $this;
    }

    public function getSerie(): ?string
    {
        return $this->Serie;
    }

    public function setSerie(?string $Serie): static
    {
        $this->Serie = $Serie;

        return $this;
    }

    public function getDateMiseEnMarche(): ?\DateTime
    {
        return $this->Date_Mise_En_Marche;
    }

    public function setDateMiseEnMarche(\DateTime $Date_Mise_En_Marche): static
    {
        $this->Date_Mise_En_Marche = $Date_Mise_En_Marche;

        return $this;
    }

    public function getPrixJour(): ?float
    {
        return $this->Prix_jour;
    }

    public function setPrixJour(float $Prix_jour): static
    {
        $this->Prix_jour = $Prix_jour;

        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): static
    {
        if (!$this->locations->contains($location)) {
            $this->locations->add($location);
            $location->setVoiture($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): static
    {
        if ($this->locations->removeElement($location)) {
            // set the owning side to null (unless already changed)
            if ($location->getVoiture() === $this) {
                $location->setVoiture(null);
            }
        }

        return $this;
    }

    public function getModele(): ?Modele
    {
        return $this->modele;
    }

    public function setModele(?Modele $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Entity\Modele;
use App\Entity\Voiture;
use App\Form\VoitureFormType;
use App\Repository\VoitureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use Symfony\Component\HttpFoundation\Request;


final class VoitureController extends AbstractController
{
    #[Route('/voitures', name: 'app_voiture')]
    public function listeVoiture(VoitureRepository $vr): Response
    {
        $voitures = $vr->findAll();
        return $this->render('voiture/listeVoiture.html.twig', [
            'listeVoiture' => $voitures,
        ]);
    }


    #[Route('addVoiture', name: 'addVoiture')]
    public function addVoiture(Request $request, EntityManagerInterface $em)
    {
        $voiture = new Voiture();
        $form= $this->createForm(VoitureFormType::class, $voiture);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('app_voiture');
        }
        return $this->render('voiture/addVoiture.html.twig', [
            'formV' => $form->createView(),
        ]);
    }

    #[Route('/voiture/{id}', name: 'voitureDelete')]
    public function delete(EntityManagerInterface $em, VoitureRepository $vr, $id): Response
    {
        $voiture = $vr->find($id);
        $em->remove($voiture);
        $em->flush();

        return $this->redirectToRoute('app_voiture');
    }


    #[Route('/updateVoiture/{id}', name: 'voitureUpdate')]
    public function updateVoiture(Request $request, EntityManagerInterface $em,
                                  VoitureRepository $vr, $id): Response
    {
        $voiture = $vr->find($id);

        $editform =$this->createForm(VoitureFormType::class, $voiture);
        $editform->handleRequest($request);
        if ($editform->isSubmitted() && $editform->isValid()) {
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('app_voiture');
        }

        return $this->render('voiture/updateVoiture.html.twig', [
            'editFormVoiture' => $editform->createView()
        ]);

    }

    #[Route('/voitures-par-modele', name: 'voitures_par_modele')]
    public function voitureParModele(Request $request, VoitureRepository $vr, EntityManagerInterface $em): Response
    {
        $modeleId = $request->query->get('modeleId'); // safer than get()
        $voitures = [];

        if ($modeleId) {
            $voitures = $vr->findByModele((int)$modeleId);
        }

        $modeles = $em->getRepository(Modele::class)->findAll();

        return $this->render('voiture/voituresParModele.html.twig', [
            'voitures' => $voitures,
            'modeles' => $modeles,
            'selectedModele' => $modeleId
        ]);
    }

}

templates/voiture/addVoiture.html.twig
<form method="post">
    {{ from_wiget(formV) }}
    <input type="submit" value="addVoiture">
</form>

templates/voiture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VoitureController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/xampp/htdocs/Symfony/tp4/src/Controller/VoitureController.php</code></li>
        <li>Your template at <code>C:/xampp/htdocs/Symfony/tp4/templates/voiture/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/voiture/listeVoiture.html.twig
<h1>Listes des voitures</h1>
<table border="1">
    <tr>
        <td>Serie</td>
        <td>Date Mise en Marche</td>
        <td>Modele</td>
        <td>Prix par jour</td>
    </tr>
    {%  for v in listeVoiture %}
    <tr>
        <td>{{ v.serie }}</td>
        <td>{{ v.dateMiseEnMarche | date('Y-m-d') }}</td>
        <td>{{ v.modele }}</td>
        <td>{{ v.prixJour }}</td>
    </tr>
    {% endfor %}
</table>

templates/voiture/voituresParModele.html.twig
<h1>Voitures par modèle</h1>

<form method="get">
    <select name="modeleId">
        <option value="">-- Selectionner un modele--</option>
        {% for m in modeles %}
            <option value="{{ m.id }}" {% if m.id == selectedModele %}selected{%  endif %}>{{ m.libelle }}</option>
        {%  endfor %}
    </select>
    <button type="submit">Filtrer</button>
</form>

{% if voitures %}
    <h2>Résultats :</h2>
    <ul>
        {% for v in voitures %}
            <li>{{ v.serie }} | {{ v.dateMiseEnMarche|date('Y-m-d') }} | {{ v.modele.libelle }} | {{ v.prixJour }}$</li>
        {% endfor %}
    </ul>

{% elseif selectedModele %}
    <p>Aucune voiture trouvée pour ce modèle</p>
{% endif %}